zoom.setup_test ... ok
Doctest: zoom.api.API ... ok
Doctest: zoom.buckets.Bucket ... FAIL

======================================================================
FAIL: Doctest: zoom.buckets.Bucket
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for zoom.buckets.Bucket
  File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 20, in Bucket

----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 23, in zoom.buckets.Bucket
Failed example:
    system.setup('../../..')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[1]>", line 1, in <module>
        system.setup('../../..')
      File "/home/herb/work/source/libs/datazoomer/zoom/system.py", line 59, in setup
        raise Exception('instance missing %s' % os.path.abspath(instance_path))
    Exception: instance missing /home/herb/work/source
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 24, in zoom.buckets.Bucket
Failed example:
    path = os.path.join(system.site.data_path, 'buckets')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[2]>", line 1, in <module>
        path = os.path.join(system.site.data_path, 'buckets')
    AttributeError: 'NoneType' object has no attribute 'data_path'
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 28, in zoom.buckets.Bucket
Failed example:
    bucket = Bucket(path, new_id)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[5]>", line 1, in <module>
        bucket = Bucket(path, new_id)
    NameError: name 'path' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 29, in zoom.buckets.Bucket
Failed example:
    item_id = bucket.put('some data')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[6]>", line 1, in <module>
        item_id = bucket.put('some data')
    NameError: name 'bucket' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 30, in zoom.buckets.Bucket
Failed example:
    item_id
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[7]>", line 1, in <module>
        item_id
    NameError: name 'item_id' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 32, in zoom.buckets.Bucket
Failed example:
    bucket.get(item_id)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[8]>", line 1, in <module>
        bucket.get(item_id)
    NameError: name 'bucket' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 34, in zoom.buckets.Bucket
Failed example:
    bucket.exists(item_id)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[9]>", line 1, in <module>
        bucket.exists(item_id)
    NameError: name 'bucket' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 36, in zoom.buckets.Bucket
Failed example:
    bucket.delete(item_id)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[10]>", line 1, in <module>
        bucket.delete(item_id)
    NameError: name 'bucket' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 37, in zoom.buckets.Bucket
Failed example:
    bucket.exists(item_id)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[11]>", line 1, in <module>
        bucket.exists(item_id)
    NameError: name 'bucket' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 40, in zoom.buckets.Bucket
Failed example:
    item_id = bucket.put('%r'%range(10))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[12]>", line 1, in <module>
        item_id = bucket.put('%r'%range(10))
    NameError: name 'bucket' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 41, in zoom.buckets.Bucket
Failed example:
    item_id
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[13]>", line 1, in <module>
        item_id
    NameError: name 'item_id' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 43, in zoom.buckets.Bucket
Failed example:
    bucket.exists(item_id)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[14]>", line 1, in <module>
        bucket.exists(item_id)
    NameError: name 'bucket' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 45, in zoom.buckets.Bucket
Failed example:
    bucket.get(item_id)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[15]>", line 1, in <module>
        bucket.get(item_id)
    NameError: name 'bucket' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 47, in zoom.buckets.Bucket
Failed example:
    bucket.delete(item_id)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[16]>", line 1, in <module>
        bucket.delete(item_id)
    NameError: name 'bucket' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 49, in zoom.buckets.Bucket
Failed example:
    bucket = Bucket(path, new_id)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[17]>", line 1, in <module>
        bucket = Bucket(path, new_id)
    NameError: name 'path' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 50, in zoom.buckets.Bucket
Failed example:
    bucket.put('some data')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[18]>", line 1, in <module>
        bucket.put('some data')
    NameError: name 'bucket' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 52, in zoom.buckets.Bucket
Failed example:
    bucket.put('some more data')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[19]>", line 1, in <module>
        bucket.put('some more data')
    NameError: name 'bucket' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 54, in zoom.buckets.Bucket
Failed example:
    sorted(bucket.keys())
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[20]>", line 1, in <module>
        sorted(bucket.keys())
    NameError: name 'bucket' is not defined
----------------------------------------------------------------------
File "/home/herb/work/source/libs/datazoomer/zoom/buckets.py", line 56, in zoom.buckets.Bucket
Failed example:
    for item_id in bucket.keys():
        bucket.delete(item_id)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zoom.buckets.Bucket[21]>", line 1, in <module>
        for item_id in bucket.keys():
    NameError: name 'bucket' is not defined


----------------------------------------------------------------------
Ran 3 tests in 2.298s

FAILED (failures=1)
